---
- name: Install default nginx server
  apt: name={{ item }} state=installed update_cache=yes
  with_items:
  - nginx

- name: Removing default vhosts
  file: >
    path="{{ item }}"
    state=absent
  with_items:
  - "/etc/nginx/sites-available/default"
  - "/etc/nginx/sites-enabled/default"
  notify:
  - restart nginx