---
- include: install_phusion.yml
  tags: nginx_install-phusion

- include: install_default.yml
  tags: nginx_install-default

- include: add_virtualhost.yml
  tags: nginx_add-virtualhost

- name: Copy passenger_wsgi to remote host
  template: >
    src="{{ nginx.passenger_wsgi_template }}"
    dest={{ project.root }}/passenger_wsgi.py
    owner="{{ deployment.permissions.owner }}"
    group="{{ deployment.permissions.group }}"
  tags: nginx_phusion-flask-passengerfile
  notify: Restat nginx

- name: Restat nginx
  service: name=nginx state=restarted
  tags: nginx_restart