---
# In vbox https://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-vagrant.box, there is no
# python 2.7 by default, so Ansible will not work until we install it, we will get an error like
# {"changed": false, "failed": true, "module_stderr": "/bin/sh: 1: /usr/bin/python: not found\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}
# Also this step is mandatory to work with AWS EC2 instances (Ubuntu 16.04 LTS)
- name: Install Python 2.7 (mandatory for Ansible)
  raw: sudo apt-get update -qq && sudo apt-get install -qq python2.7
  tags: system_install-python-27

- include: set_locales.yml
  tags: system_set-locales

- include: add_new_users.yml
  tags: system_add-new-users

- include: add_ssh_keys.yml
  tags: system_add-ssh-keys

- include: upgrade_packages.yml
  tags: system_upgrade-packages

- name: Install apt dependencies
  apt: name={{ item }} state=installed update_cache=yes
  with_items: "{{ system.dependencies.apt }}"
  when: system.dependencies.apt is defined
  tags: system_install-apt-dependencies