---
- name: System-soft, Postfix | Set Postfix option type as internet site
  debconf: 
    name=postfix
    question="postfix/main_mailer_type"
    value="'Internet Site'"
    vtype="string"

- name: System-soft, Postfix | Installing postfix package
  apt: name=mailutils state=installed update_cache=yes

# To try:
# echo "Message Body" | mail -s "Message Subject" myemail@myserver.com