---
- include: msmtp.yml
  tags: system-soft_install_msmtp

- include: mailserver.yml
  tags: system-soft_install_mailserver

- include: fail2ban.yml
  tags: system-soft_install_fail2ban

# Valid, for example, to unzip uploads folder in Wordpress
- name: Install unzip
  apt: name="unzip" state=installed update_cache=yes
  tags: system-soft_install_unzip