---
- name: Python | Installing virtualenv
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  with_items:
    - "python-pip"
    - "virtualenv"
  tags: python_install-virtualenv

- name: Python | Install requirements.txt
  pip: 
    requirements={{ project.root }}/requirements.txt
    virtualenv={{ project.root }}/venv
  tags: python_install-requirements
