---
- name: Add Mongo PPA key
  apt_key: >
    keyserver=hkp://keyserver.ubuntu.com:80
    id=EA312927
    state=present

- name: Add mongoDB sources list
  lineinfile: >
    line="deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse"
    dest=/etc/apt/sources.list.d/mongodb-org-3.2.list
    state=present
    create=yes