---
- include: prepare_install.yml

- name: PostgreSQL | Install Client
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  with_items:
    - "postgresql-client-9.6"
    - "postgresql-common"
    - "libpq-dev"