---
# The standard ca-certs are needed because  without them apt_key will fail to
# validate www.postgresql.org (or probably any other source).
- name: PostgreSQL, installing dev server | Make sure the CA certificates are available
  apt:
    pkg: ca-certificates
    state: present

- name: PostgreSQL, installing dev server | Add PostgreSQL repository apt-key
  apt_key:
    id: "ACCC4CF8"
    url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
    state: present

- name: PostgreSQL | Add PostgreSQL repository
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main"
    state: present
    mode: 644

- name: PostgreSQL | Make sure the dependencies are installed
  apt:
    pkg: "{{item}}"
    state: present
    update_cache: yes
  with_items: ["python-psycopg2", "python-pycurl", "locales"]

# To test postgresql version: psql -V